version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@0.0.10
  docker: circleci/docker@1.4.0
  node: circleci/node@3.0.1

workflows:
  test-and-publish:
    jobs:
      - node/test

      - hold:
          type: approval

      - docker/publish:
          filters:
            branches:
              only:
                - master
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - node/test
          tag: "${CIRCLE_SHA1},latest"

      - aws-ecs/deploy-service-update:
          container-image-name-updates: "container=react-template,tag=${CIRCLE_SHA1}"
          cluster-name: "react-template"
          family: "react-template" # Family name must match service name
          filters:
            branches:
              only:
                - master
          requires:
            - hold
            - docker/publish
